version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myuser
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - mynetwork

  redis:
    image: redis:7.0.11
    ports:
      - '6379:6379'
    networks:
      - mynetwork

  configserver:
    container_name: configserver
    image: joseph24x7/configserver:latest
    ports:
      - 8888:8888
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/myuser
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge