server:
  port: 8082

spring:
  datasource:
    url: ${datasource.url:}
    username: ${datasource.username:}
    password: ${datasource.password:}
  jpa:
    hibernate:
      ddl-auto: ${jpa.hibernate.ddl-auto:}
    show-sql: true
    properties:
      hibernate:
        dialect: ${jpa.properties.hibernate.dialect:}