properties:
  secret-key: 405F735266556A586E3272357538782F413F4428472B4B6250645367566B5970
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myuser
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379