server:
  port: 8082
properties:
  secret-key: ${secret-key:}
spring:
  security:
    user:
      name: secret_token
      password: stagingnslfjbljbfjbfhgjdklsRYEWSHJ32UUpuujKn
  mail:
    host: ${mail.host:}
    port: ${mail.port:}
    username: ${mail.username:}
    password: ${mail.password:}
  datasource:
    url: ${datasource.url:}
    username: ${datasource.username:}
    password: ${datasource.password:}
  jpa:
    hibernate:
      ddl-auto: ${jpa.hibernate.ddl-auto:}
    show-sql: true
    properties:
      hibernate:
        dialect: ${jpa.properties.hibernate.dialect:}