server:
  port: 8082
properties:
  secret-key: ${secret-key:}
spring:
  mail:
    host: ${mail.host:}
    port: ${mail.port:}
    username: ${mail.username:}
    password: ${mail.password:}
    properties.mail.smtp.auth: ${mail.properties.mail.smtp.auth:}
    properties.mail.smtp.starttls.enable: ${mail.properties.mail.smtp.starttls.enable:}
  datasource:
    url: ${datasource.url:}
    username: ${datasource.username:}
    password: ${datasource.password:}
  jpa:
    hibernate:
      ddl-auto: ${jpa.hibernate.ddl-auto:}
    show-sql: true
    properties:
      hibernate:
        dialect: ${jpa.properties.hibernate.dialect:}